#!/bin/bash
jq -f -r v3.jq filename > logfiltrado
jq -r '"\(.nome), \(.date), \(.text)"' logfiltrado > logtudo
#encurtar nomes para exibir tudo melhor no v3 - nomes ficticios
sed -i 's/José/| zé/g; s/Giovanni/| gigio/g; s/Fiat/| marea/g; s/Frank/| zappa/g' logtudo
